### ISSUE TITLE
Jason Dion's udemy.com links no longer working

### ISSUE THREAD

**Issue by DushanthaS** [aaronshaf/security-plus#2]
Seems to be urls changed from "comptia-security" to "securityplus".

For example 
https://www.udemy.com/program/comptia-security/learn/2015076/lecture/12836814#overview
is now 
https://www.udemy.com/course/securityplus/learn/lecture/12836814#overview

I can push a change if you want.

**Comment by aaronshaf** [comment]
@DushanthaS Please feel free to
